# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch

import torch
# Create random tensor
tensor_random=torch.rand(7,7)
tensor_random


tensor([[0.9221, 0.6848, 0.1588, 0.4780, 0.7760, 0.9604, 0.0278],
        [0.7122, 0.0849, 0.3887, 0.2403, 0.9826, 0.5695, 0.7015],
        [0.4466, 0.3507, 0.5529, 0.0020, 0.8053, 0.4123, 0.3616],
        [0.1480, 0.0809, 0.6277, 0.0372, 0.1972, 0.8696, 0.2076],
        [0.2683, 0.4252, 0.4861, 0.2878, 0.4752, 0.9859, 0.1149],
        [0.3294, 0.0336, 0.8321, 0.5402, 0.6637, 0.2038, 0.0532],
        [0.6213, 0.0733, 0.6996, 0.3818, 0.8450, 0.6568, 0.8495]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_Y_random=torch.rand(1,7)
transpose_Y=tensor_Y_random.t()
res=torch.matmul(tensor_random,transpose_Y)
res,res.shape
# Perform matrix multiplication


(tensor([[1.6112],
         [1.1535],
         [0.9288],
         [0.5548],
         [1.0874],
         [0.9995],
         [1.2147]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x=torch.rand(7,7)
y=torch.rand(1,7)
y_transpose=y.t()

# Matrix multiply tensors
final=torch.matmul(x,y_transpose)
final,final.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
a=torch.rand(2,3).to(device)
b=torch.rand(2,3).to(device)
a,b

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
b_T=b.t()
myres=torch.matmul(a,b_T)
myres,myres.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
max_value=torch.max(myres)
# Find min
min_value=torch.min(myres)
max_value,min_value

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
pos_max=torch.argmax(myres)

# Find arg min
pos_min=torch.argmin(myres)
pos_max,pos_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)
# Create random tensor
c=torch.rand([1,1,1,10])


# Remove single dimensions
c_squeezed=c.squeeze()

# Print out tensors and their shapes
print(c),print(c.shape)
c_squeezed,c_squeezed.shape

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))